# -*- coding: utf-8 -*-
"""Desafio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vjjWpjC2YPP_MY6ALpynk3W1gN6aBCZU
"""

#importar bibliotecas
from google.colab import files
from io import BytesIO

#biblioteca para trabalhar com imagens
from PIL import Image 

#fazer leitura da imagem salva em meu computador
uploaded = files.upload()
im = Image.open(BytesIO(uploaded['Syngenta.bmp']))
pixval = im.load()

rgb_im = im.convert('RGB') #converter as cores para RGB
columnsize, rowsize = im.size #guardar dimensões da img
count = 0 #variavel para armazenar a quantidade pixel verdes contados

for i in range(columnsize):
  for j in range(rowsize):
    r, g, b = rgb_im.getpixel((i, j))
    #print("(", r, ",", g, ",", b, ")")

    if (r == 96) and (g == 192) and (b == 0):
      count = count + 1

print("Foram encontrado ", count, "pixels verdes (RGB(96, 192, 0))")